s = "Hello, World"
print(s.upper(), s.lower())
print("  pad  ".strip(), "|" + "  pad  ".lstrip() + "|", "|" + "  pad  ".rstrip() + "|")
print(s.startswith("Hello"), s.endswith("World"), s.startswith("x"))
print(s.replace("l", "L"))
print(s.split(", "))
print("a b  c".split())
print(",".join(["a", "b", "c"]), "".join(["x", "y"]))
print(s.count("l"), s.count("zz"))
print(s.find("World"), s.find("zz"), s.index("World"))
print("123".isdigit(), "12a".isdigit(), "".isdigit())
print("abc".isalpha(), "ab1".isalpha())
print("  ".isspace(), "a ".isspace())
print("a,,b".split(","))
