#!/usr/bin/env python3
"""Generate `basic/float_repr_test.mbt` from CPython.

Python's `repr` of a float is laid out by rules MoonBit's `Double::to_string`
does not share, and the layout shows up in three places: the AST dump, the
`print` of a float, and the `repr` inside a container. This table is the whole
claim, and it is generated from CPython so it cannot drift.

Each row is a 64-bit pattern and the string CPython prints, so the table needs
no parsing on either side and covers values no literal can spell.

Regenerate with `just float-cases`; the diff is the review artifact.
"""

import math
import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "basic" / "float_repr_test.mbt"

VALUES = [
    0.0, -0.0, 1.0, -1.0, 0.5, -0.5, 2.0, 10.0, 100.0, 1e5,
    0.1, 0.2, 0.1 + 0.2, 1 / 3, 2 / 3, math.pi, math.e,
    1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 2.5e-7,
    1e13, 1e14, 1e15, 1e16, 1e17, 1.2345678901234567e17,
    1e100, 1e300, 1e308, 1.7976931348623157e308,
    1e-100, 1e-300, 1e-308, 5e-324, 2.2250738585072014e-308,
    123456789.0, 1234567890123456.0, 12345678901234567.0,
    -1.5e-8, 3.0, 7.0 / 2, 1e16 + 2, 9007199254740992.0,
    float("inf"), float("-inf"), float("nan"),
    1.5, 2.5, 1e-7, 1.0000000000000002, 4.9e-324,
    6.02e23, 1.602e-19, 0.30000000000000004, 8.0, 1024.0,
]
# Powers of ten around both thresholds, where the layout switches.
VALUES += [float(f"1e{e}") for e in range(-10, 20)]
VALUES += [float(f"9.99e{e}") for e in range(-8, 18)]


def main() -> None:
    seen = set()
    rows = []
    for v in VALUES:
        bits = struct.unpack(">Q", struct.pack(">d", v))[0]
        if bits in seen:
            continue
        seen.add(bits)
        rows.append(f'  (0x{bits:016X}UL, "{repr(v)}"),')

    body = "\n".join(rows)
    OUT.write_text(f'''// Generated by tools/gen_float_cases.py from CPython. DO NOT EDIT.
//
// A 64-bit pattern and the string CPython's `repr` prints for it. Covers both
// layout thresholds, the subnormals, the infinities, the two zeros and the
// values whose shortest digits are famously awkward.

///|
let float_cases : Array[(UInt64, String)] = [
{body}
]

///|
test "every float prints the way CPython prints it" {{
  for case in float_cases {{
    let (bits, want) = case
    let d = bits.reinterpret_as_double()
    assert_eq(@basic.py_float_repr(d), want, msg="bits 0x\\{{bits}}")
  }}
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} values)")


if __name__ == "__main__":
    main()
