#!/usr/bin/env python3
"""Generate `token/number_table_test.mbt` from CPython.

Every numeric literal the tokenizer must read, with the value CPython gives
it. An integer is compared as its decimal string, which is exact; a float is
compared as its 64-bit pattern, which is exact and needs no `repr` -- Python's
float repr is Phase 7's problem, and this table must not depend on it.

A literal CPython refuses is recorded as an expected failure, so that accepting
one is a test failure rather than a silence.

Regenerate with `just number-cases`; the diff is the review artifact.
"""

import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "lib" / "lexer" / "number_table_test.mbt"

CASES = [
    "0", "00", "000", "1", "7", "42", "1_000", "1_000_000",
    "1000000000000000000000000000000000000000",
    "0x0", "0xff", "0xFF", "0XfF", "0x_ff", "0x_FF_ff", "0xdead_beef",
    "0o0", "0o17", "0O17", "0o_17", "0o777",
    "0b0", "0b1", "0b1_0", "0B1010", "0b_1_0",
    "0.0", "1.0", "1.", ".5", "0.5", "1.5", "3.14159",
    "1e10", "1E10", "1e+10", "1e-10", "1.5e3", "1.e3", ".5e3",
    "1_0.0_1e-1_0", "1e308", "1e-308", "5e-324", "1.7976931348623157e308",
    "0.1", "0.2", "0.3", "100.0", "1e16", "1e15",
    "1j", "1.5j", "0j", "3J", "1e10j",
    # Refused by CPython: the first two by the tokenizer, the last by the parser.
    "1__0", "0_", "09", "01", "0_1",
]


def value(lit: str):
    try:
        v = eval(lit)  # noqa: S307 - literals only, from the list above
    except SyntaxError:
        return None
    return v


def main() -> None:
    rows = []
    for lit in CASES:
        v = value(lit)
        if v is None:
            rows.append(f'  ("{lit}", Refused),')
        elif isinstance(v, int):
            rows.append(f'  ("{lit}", WantInt("{v}")),')
        elif isinstance(v, complex):
            bits = struct.unpack(">Q", struct.pack(">d", v.imag))[0]
            rows.append(f'  ("{lit}", WantImaginary(0x{bits:016X}UL)),')
        else:
            bits = struct.unpack(">Q", struct.pack(">d", v))[0]
            rows.append(f'  ("{lit}", WantFloat(0x{bits:016X}UL)),')

    body = "\n".join(rows)
    OUT.write_text(f'''// Generated by tools/gen_number_cases.py from CPython. DO NOT EDIT.
//
// Every numeric literal the tokenizer must read and the value CPython gives
// it: an integer as its decimal string, a float as its 64-bit pattern (exact,
// and independent of anyone's `repr`), a refused literal as `Refused`.

///|
priv enum Expect {{
  WantInt(String)
  WantFloat(UInt64)
  WantImaginary(UInt64)
  Refused
}}

///|
let cases : Array[(String, Expect)] = [
{body}
]

///|
test "every numeric literal reads as CPython reads it" {{
  for case in cases {{
    let (lit, want) = case
    let source = "x = " + lit + "\\n"
    let got = try {{
      let tokens = @lexer.lex_string(source)
      Some(tokens[2].number_value())
    }} catch {{
      _ => None
    }}
    match (want, got) {{
      (Refused, None) => ()
      (Refused, Some(_)) => fail("\\{{lit}}: CPython refuses it and we did not")
      (_, None) => fail("\\{{lit}}: we refused it and CPython does not")
      (WantInt(text), Some(Int(n))) => assert_eq(n.to_string(), text, msg=lit)
      (WantFloat(bits), Some(Float(d))) =>
        assert_eq(d.reinterpret_as_uint64(), bits, msg=lit)
      (WantImaginary(bits), Some(Imaginary(d))) =>
        assert_eq(d.reinterpret_as_uint64(), bits, msg=lit)
      (_, Some(_)) => fail("\\{{lit}}: the wrong kind of number")
    }}
  }}
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} cases)")


if __name__ == "__main__":
    main()
