#!/usr/bin/env python3
"""Generate `lexer/string_table_test.mbt` from CPython.

Every string and bytes literal whose decoding could go wrong, with the value
CPython gives it -- as a list of code points, so the table does not depend on
anyone's `repr`. A literal CPython refuses is recorded as refused.

Regenerate with `just string-cases`; the diff is the review artifact.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "lexer" / "string_table_test.mbt"

CASES = [
    # plain
    '""', "''", '"a"', "'a'", '"ab c"',
    # both quotes inside the other
    '"it\'s"', '\'say "hi"\'',
    # named escapes
    r'"\n"', r'"\t"', r'"\r"', r'"\\"', r'"\'"', r'"\""',
    r'"\a"', r'"\b"', r'"\f"', r'"\v"',
    # octal and hex
    r'"\0"', r'"\7"', r'"\10"', r'"\101"', r'"\377"', r'"\x41"', r'"\x00"', r'"\xff"',
    # unicode
    r'"é"', r'"€"', r'"\U0001F40D"', r'"\N{BULLET}"',
    # an escape Python does not know keeps its backslash
    r'"\d"', r'"\q\w"',
    # a backslash-newline disappears
    '"a\\\n b"',
    # raw: nothing is decoded, and a backslash still defers the quote
    r'r"\n"', r'r"\\"', r'R"a\"b"', r'r"\x41"',
    # prefixes in every case
    'u"x"', 'U"x"', 'b"x"', 'B"x"', r'rb"\x41"', r'bR"\n"', r'Br"\n"', r'RB"\n"',
    # triple quotes, including quotes inside
    '"""a"""', "'''a'''", '"""a\nb"""', '"""say "hi\""""', '""""""',
    # non-ASCII, literally
    '"héllo"', '"🐍"', '"日本語"',
]


def main() -> None:
    rows = []
    for lit in CASES:
        try:
            v = eval(lit)  # noqa: S307 - literals only, from the list above
        except (SyntaxError, ValueError):
            rows.append(f"  ({lit_repr(lit)}, Refused),")
            continue
        if isinstance(v, bytes):
            pts = ", ".join(str(b) for b in v)
            rows.append(f"  ({lit_repr(lit)}, WantBytes([{pts}])),")
        else:
            pts = ", ".join(str(ord(c)) for c in v)
            rows.append(f"  ({lit_repr(lit)}, WantStr([{pts}])),")

    body = "\n".join(rows)
    OUT.write_text(f'''// Generated by tools/gen_string_cases.py from CPython. DO NOT EDIT.
//
// Every string and bytes literal whose decoding could go wrong, and the value
// CPython gives it -- as code points, so the table depends on no one's `repr`.

///|
priv enum Want {{
  WantStr(Array[Int])
  WantBytes(Array[Int])
  Refused
}}

///|
let string_cases : Array[(String, Want)] = [
{body}
]

///|
test "every string literal decodes as CPython decodes it" {{
  for case in string_cases {{
    let (lit, want) = case
    let source = "x = " + lit + "\\n"
    let got = try {{
      let tokens = @lexer.lex_string(source)
      let t = tokens[2]
      if t.kind is Bytes(_) {{
        Some(("bytes", t.bytes_value().to_array().map(fn(b) {{ b.to_int() }})))
      }} else {{
        Some(("str", t.str_value().to_array().map(fn(c) {{ c.to_int() }})))
      }}
    }} catch {{
      _ => None
    }}
    match (want, got) {{
      (Refused, None) => ()
      (Refused, Some(_)) => fail("\\{{lit}}: CPython refuses it and we did not")
      (_, None) => fail("\\{{lit}}: we refused it and CPython does not")
      (WantStr(points), Some(("str", got_points))) =>
        assert_eq(got_points, points, msg=lit)
      (WantBytes(points), Some(("bytes", got_points))) =>
        assert_eq(got_points, points, msg=lit)
      (_, Some(_)) => fail("\\{{lit}}: str where bytes were wanted, or the reverse")
    }}
  }}
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} cases)")


def lit_repr(lit: str) -> str:
    """The literal itself, as a MoonBit string literal."""
    out = ['"']
    for c in lit:
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif c == "\n":
            out.append("\\n")
        else:
            out.append(c)
    out.append('"')
    return "".join(out)


if __name__ == "__main__":
    main()
