#!/usr/bin/env python3
"""Generate `value/repr_table_test.mbt` from CPython.

`repr` and `str` of every kind of value PurePy can print, as nested source
expressions with CPython's answers. Strings with both quotes, escapes,
non-ASCII, control characters; containers nested; the empty forms.

Regenerate with `just tables`; the diff is the review artifact.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "lib" / "value" / "repr_table_test.mbt"

CASES = [
    "None", "True", "False", "0", "-1", "10000000000000000000000",
    "0.0", "-0.0", "1.0", "1e16", "1e-5", "0.1 + 0.2", "1e400", "-1e400",
    '""', '"a"', '"it\'s"', '\'say "hi"\'', '"both \' and \\""',
    r'"tab\there"', r'"nl\nhere"', r'"cr\rhere"', r'"back\\slash"',
    r'"null\x00here"', r'"bell\x07"', r'"esc\x1b"', r'"del\x7f"',
    '"héllo"', '"日本語"', '"🐍"', r'"\xa0"', r'"\xad"', '"\\xff"',
    "[]", "[1]", "[1, 2]", "[[1], [2, [3]]]",
    "()", "(1,)", "(1, 2)", "((1,), (2, 3))",
    "{}", '{"a": 1}', '{"a": 1, "b": 2}', '{"a": [1, (2,)]}',
    '[1, "a", (2, 3), {"k": 1.5}, None, True]',
    '["it\'s", \'say "hi"\']',
]


def mbt_string(s: str) -> str:
    out = ['"']
    for c in s:
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif c == "\n":
            out.append("\\n")
        elif c == "\r":
            out.append("\\r")
        elif c == "\t":
            out.append("\\t")
        elif ord(c) < 0x20 or ord(c) == 0x7F:
            out.append(f"\\u{{{ord(c):04X}}}")
        else:
            out.append(c)
    out.append('"')
    return "".join(out)


def main() -> None:
    rows = []
    for expr in CASES:
        v = eval(expr)  # noqa: S307 - literal expressions from the list above
        rows.append(
            f"  ({mbt_string(expr)}, {mbt_string(repr(v))}, {mbt_string(str(v))}),"
        )
    OUT.write_text(f'''// Generated by tools/gen_repr_cases.py from CPython. DO NOT EDIT.
//
// An expression, CPython's `repr` of its value, and CPython's `str`. The two
// differ only for a string, which `print` writes bare and a container writes
// quoted.

///|
let repr_cases : Array[(String, String, String)] = [
{chr(10).join(rows)}
]

///|
test "repr and str agree with CPython on every kind of value" {{
  for case in repr_cases {{
    let (expr, want_repr, want_str) = case
    let v = match value_of(expr) {{
      Some(v) => v
      None => {{
        fail("\\{{expr}}: did not evaluate")
        continue
      }}
    }}
    assert_eq(v.repr().unwrap(), want_repr, msg=expr)
    assert_eq(v.str().unwrap(), want_str, msg=expr)
  }}
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} values)")


if __name__ == "__main__":
    main()
